# Generated by Django 4.2 on 2026-01-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodsugarrecord',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodsugarrecord',
            name='food_item',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bloodsugarrecord',
            name='insulin_units',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodsugarrecord',
            name='time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
